#!/usr/bin/env bash
# A Script that will display information about subdomains.


digging() {
    dig=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | tr '.' ' ')
    echo "$2 $dig" | awk '{print "The subdomain " $1 " is a " $7 " record and points to "$8"."$9"."$10"."$11 }'
}

if [ "$#" -eq 1 ]
then
    digging "$1" "www"
    digging "$1" "lb-01"
    digging "$1" "web-01"
    digging "$1" "web-02"
elif [ "$#" -eq 2 ]
then
    digging "$1" "$2"
fi
