#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get update
apt-get -y install nginx

# Nginx listens by default on Port 80.
# ufw firewall to get requests
ufw allow 'Nginx HTTP'

# Create Directory and Change Ownership
mkdir -p /var/www/html
touch /var/www/html/404.html

chown -R "$USER":"$USER" /var/www/html/index.html
chown -R "$USER":"$USER" /var/www/html/404.html

# Page Content
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" >/var/www/html/404.html

SERVER_CONFIG="server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
            return 301 https://www.youtube.com/watch?v=OcVmaIlHZ1o;
        }

        error_page 404 /404.html;
            location /404.html {
                root /var/www/html;
                internal;
            }

}"

echo -e "$SERVER_CONFIG" > /etc/nginx/sites-enabled/default

sudo nginx -t
service nginx restart
