#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy


server_config=\
"
frontend emmy-frontend
	bind *:80
	mode http
	default_backend donnie-backend
backend donnioe-backend
	balance roundrobin
	server 80121-web-01 34.232.52.250 check
	server 80121-web-02 100.24.237.16 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
