#!/usr/bin/env bash
# Displays "Hi" after the 9th one
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	counter=$((counter + 1))
done
