#!/usr/bin/env bash
# Prints 1 to 20; "bad luck from China JKapan and Italy"
counter=1
while [ $counter -le 20 ]
do
	case $counter in
		4)
			echo "$counter"
			echo "bad luck from China"
			;;
		9)
			echo "$counter"
			echo "bad luck from Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
	esac
	counter=$((counter + 1))
done
