#!/usr/bin/env bash
# Display time in hours and minutes
hour=0
minute=1
while [ $hour -lt 12 ]; do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
