#!/usr/bin/env bash
# Iterate through the file in the current directory(Excluding hidden files)
for file in *
do
	if [ ! -d "$file" ] && [[ "$file" != .* ]]
	then
		name_after_dash=$(echo "$file" | cut -d '-' -f 2=)
		echo "$name_after_dash"
	fi
done
