#!/usr/bin/env bash

# check if an argument is provided
if [ $# -eq 0 ]; then
	echo "Usage: $0 <username>"
	exit 1
fi
# Get the username from the command line argument
username=$1

# run the whoami command under the specified user
sudo -u $username whoami
