#!/usr/bin/env bash

# Set the nginx user in the nginx.conf file
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Modify the default site configuration to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

# Display the status to verify the changes
service nginx status
