#!/usr/bin/env bash

# Set the nginx user in the nginx.conf file
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Modify the default site configuration to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

# apache may interfere with nginx so kill the process if it is running
pkill apache2

# Restart Nginx to apply the changes
sudo -u nginx service nginx start

# Display the status to verify the changes
service nginx status
